server:
  port: 8086
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server    

  datasource:
    url: jdbc:postgresql://localhost:5432/ead_notification2
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always   
  rabbitmq:
    addresses: amqps://mjwtccin:EYeEwbQqfATRAAWY9mjhIPmacx0Ewfvv@toad.rmq.cloudamqp.com/mjwtccin   
    
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationCommand
    queue:
      notificationCommandQueue:
        name: ead.notificationCommand.ms.notification
    key:
      notificationCommandKey: ms.notification
          

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health 
              
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost                    
