
server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_course
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
    
ead:
  api:
    url:
      authuser: 'http://localhost:8087'