server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BillyAlexander/ead-config-server-micro
          default-label: main
          username: BillyAlexander
          password: '*****************' 


ead:
  serviceRegistre:
    userName: serviceRegistre
    password: 'ead123sr'
        
eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistre.userName}:${ead.serviceRegistre.password}@localhost:8761/eureka'
  instance:
    hostname: localhost    