server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BillyAlexander/ead-config-server-micro
          default-label: main
          username: BillyAlexander
          password: Password for authentication with remote repository. 
    
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost    